// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvPMfEl-xtLPSrNkgYtMjj7lMomOQHis',
    appId: '1:129250390098:web:6017dfe7dddfe179d0af8b',
    messagingSenderId: '129250390098',
    projectId: 'assessment-76c1e',
    authDomain: 'assessment-76c1e.firebaseapp.com',
    storageBucket: 'assessment-76c1e.appspot.com',
    measurementId: 'G-9SSZZZF4G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8RtnB4j3FK9QVPu2EKn-E1jQKIyHnsg',
    appId: '1:129250390098:android:722836ab9361a4ded0af8b',
    messagingSenderId: '129250390098',
    projectId: 'assessment-76c1e',
    storageBucket: 'assessment-76c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlC8w4Ll4m_exMJTJ4PtLVqwJ5Xt_mKk',
    appId: '1:129250390098:ios:5fd6fb8501f416d2d0af8b',
    messagingSenderId: '129250390098',
    projectId: 'assessment-76c1e',
    storageBucket: 'assessment-76c1e.appspot.com',
    iosBundleId: 'com.example.assessment',
  );
}
